//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string article { get; set; }
        public string product_name { get; set; }
        public string unit { get; set; }
        public decimal cost { get; set; }
        public string supplier { get; set; }
        public int manufacturer { get; set; }
        public int category { get; set; }
        public Nullable<int> discount { get; set; }
        public int quantityInStock { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual manufacturer manufacturer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }

        public string OldCost
        {
            get
            {
                if (discount > 0)
                {
                    return cost.ToString();
                }
                else
                {
                    return "";
                }
            }
        }

        public decimal NewCost
        {
            get
            {
                if (discount > 0)
                {
                    // Правильное вычисление: цена - (цена * скидка / 100)
                    return Math.Round(cost - (cost * (decimal)discount / 100), 2);
                }
                else
                {
                    return cost;
                }
            }
        }



        public SolidColorBrush FonStyle
        {
            get
            {
                // Если товара нет на складе
                if (quantityInStock == 0)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("#ADD8E6"); // голубой
                }
                // Если скидка больше 15%
                else if (discount > 15)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("#2E8B57"); // зеленый
                }
                // Во всех остальных случаях - белый фон
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }
    }
}
